feature/impl
cichan02/micro-airport-location pull request #4
Opened 2023-03-12 21:20 UTC by cichan02

2023-03-13 05:42 UTC, h1alexbel requested changes

2023-03-13 05:42 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/domain/Airport.java
> +import lombok.*;
don't use *

2023-03-13 05:42 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/domain/Airport.java
> +public class Airport {
hashcode is not overridden

2023-03-13 05:42 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/persistence/impl/AirportRepositoryImpl.java
> +    private final R2dbcAirportRepository r2dbcRepository;
r2dbc prefix is redundant

2023-03-13 05:42 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/impl/CountryServiceImpl.java
> +        long legalId = id == null ? 0 : id;
better to use 
```java
if(){
} else{
}
```

2023-03-13 05:42 UTC, h1alexbel commented on src/main/resources/application.yaml
> +    user: ${spring.r2dbc.username}
don't depend on spring.r2dbc.username and password

2023-03-13 06:15 UTC, h1alexbel commented on src/main/resources/application.yaml
> -    password: ${spring.r2dbc.password}
Liquibase needs `user` and `password`. Specify them, but using env

2023-03-13 10:38 UTC, h1alexbel commented on src/main/resources/application.yaml
> +    user:
@cichan02 
empty values? or I miss something..

2023-03-14 08:53 UTC, cichan02 commented
@h1alexbel May I merge this PR? Or are you still have been reviewing?

2023-03-14 09:05 UTC, cichan02 commented
@h1alexbel May You (or I) merge this PR? Or is the review still in progress?

2023-03-14 09:27 UTC, merged