Feature/checkstyle
cichan02/micro-airport-location pull request #43
Opened 2023-05-05 07:00 UTC by cichan02

2023-05-05 07:44 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/web/dto/AirportDTO.java
> +    private static final int NAME_MAX_SIZE = 200;
It was done to avoid 'MagicNumber' from Checkstyle. Is it norm?

2023-05-05 07:58 UTC, cichan02 commented
Write full Javadocs for this service.

Suppress only auto-generated files.

2023-05-05 11:24 UTC, h1alexbel requested changes

2023-05-05 11:24 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/domain/Airport.java
> +
nice

2023-05-05 11:24 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/domain/Airport.java
> +
nice

2023-05-05 11:24 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/impl/CountryServiceImpl.java
> +
@cichan02 javadocs should be only generated for public methods, not for overridden ones

2023-05-05 11:24 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/web/dto/AirportDTO.java
> +    private static final int NAME_MAX_SIZE = 200;
@cichan02 can be suppressed

2023-05-10 05:29 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/service/impl/CountryServiceImpl.java
> +
@h1alexbel Removed javadoc from @Overridden methods

2023-05-10 06:07 UTC, h1alexbel requested changes

2023-05-10 06:07 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/persistence/impl/AirportRepositoryImpl.java
> +     * {@inheritDoc}
@cichan02 You should have no Javadocs on overriden methods

2023-05-10 06:18 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/persistence/impl/AirportRepositoryImpl.java
> +     * {@inheritDoc}
@h1alexbel Totally removed docs from overridden methods

2023-05-10 09:03 UTC, h1alexbel requested changes

2023-05-10 11:06 UTC, h1alexbel commented on checkstyle-suppressions.xml
>                files="(Mongo(Airport|City)|ErrorResponseDTO)\.java"
@cichan02 ok, but the more classes you will have in the source code the more verbose your `HiddenFiled` suppression will be

2023-05-10 11:35 UTC, cichan02 commented on checkstyle-suppressions.xml
>                files="(Mongo(Airport|City)|ErrorResponseDTO)\.java"
@h1alexbel thanks

2023-05-10 11:50 UTC, h1alexbel approved these changes

2023-05-10 11:50 UTC, h1alexbel approved these changes

2023-05-10 11:51 UTC, merged