Elasticsearch
cichan02/micro-airport-location pull request #50
Opened 2023-06-01 20:10 UTC by cichan02

2023-06-01 20:22 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/persistence/impl/AirportRepositoryImpl.java
> +    private Suggester buildSuggester(final Inquiry inquiry) {
Added private methods to prevent base method from extreme growing. Is it normal? Or it should be separate class with public methods?

2023-06-01 20:33 UTC, cichan02 commented on src/main/resources/elastic-create-indices.sh
> +#Create countries index
One-script file to create all indices with right analyzers on fields.

2023-06-02 08:27 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/persistence/impl/AirportRepositoryImpl.java
> +    private Suggester buildSuggester(final Inquiry inquiry) {
@cichan02 all the private methods can be converted into separate classes

2023-06-02 11:09 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/persistence/impl/AirportRepositoryImpl.java
> +    private Suggester buildSuggester(final Inquiry inquiry) {
@h1alexbel moved to separate classes with public methods.

2023-06-02 11:12 UTC, cichan02 commented on checkstyle-suppressions.xml
>  </suppressions>
Do more pointed suppress.

2023-06-02 12:36 UTC, h1alexbel requested changes

2023-06-02 12:36 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/persistence/util/SearchConverter.java
> +    public Set<Airport> toSet(
@cichan02 all public methods should be declared in the interface

2023-06-02 12:43 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/persistence/util/SearchConverter.java
> +    public Set<Airport> toSet(
@h1alexbel А это не перебор для просто util класса?

2023-06-02 12:50 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/persistence/util/SearchConverter.java
> +    public Set<Airport> toSet(
@h1alexbel add interfaces for this methods

2023-06-02 14:58 UTC, h1alexbel requested changes

2023-06-02 14:58 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/persistence/util/SearchConverterImpl.java
> +
add `@Override` for preventing random compile-time errors

2023-06-02 15:05 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/persistence/util/SearchConverterImpl.java
> +
added

2023-06-02 17:49 UTC, h1alexbel approved these changes

2023-06-02 17:49 UTC, merged