GraphQL
cichan02/micro-airport-location pull request #62
Opened 2023-06-12 06:41 UTC by cichan02

2023-06-12 06:50 UTC, cichan02 commented
This PR adds GraphQL API for all entities.

2023-06-12 07:59 UTC, h1alexbel requested changes
@cichan02 please see my comments

2023-06-12 07:59 UTC, h1alexbel commented on pom.xml
> +		<dependency>
@cichan02 compile scoped dependency should be located on top of the test one

2023-06-12 08:12 UTC, h1alexbel requested changes
§

2023-06-12 08:12 UTC, h1alexbel commented on pom.xml
> +			<scope>test</scope>
here you don't use enter after dependency XML node, but on `line 155` you are using enter

@cichan02 I believe this inconsistency can be harmful

2023-06-12 08:22 UTC, cichan02 commented on pom.xml
> +			<scope>test</scope>
@h1alexbel this dependencies are coming together. I mean second dependency overshadows old version of dependency inside spring-boot-starter-test to prevent vulnerability warning. That is why I don't put enter between they.

2023-06-12 09:27 UTC, h1alexbel commented on pom.xml
> +			<scope>test</scope>
@cichan02 code is not saying this

2023-06-12 09:33 UTC, cichan02 commented on pom.xml
> +			<scope>test</scope>
@h1alexbel add enters

2023-06-12 09:34 UTC, h1alexbel approved these changes
lgtm

2023-06-13 13:03 UTC, cichan02 commented
@h1alexbel Could you please merge this PR. I need this branch to pull tests for GraphQL controllers in it.

2023-06-13 14:28 UTC, h1alexbel approved these changes
lgtm

2023-06-13 14:28 UTC, merged