Tests for GraphQL API
cichan02/micro-airport-location pull request #64
Opened 2023-06-13 17:46 UTC by cichan02

2023-06-13 17:52 UTC, cichan02 commented
This PR adds tests for GraphQL controllers and also brings **Fakes** for services.

2023-06-14 10:32 UTC, h1alexbel requested changes

2023-06-14 10:32 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/persistence/mongo/MongoAirportRepository.java
> +@Profile("!test")
@cichan02 create main profile instead

2023-06-14 10:32 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/fake/AirportServiceFake.java
> +public class AirportServiceFake implements AirportService {
I believe that fake prefix should be first

2023-06-14 10:32 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/fake/CountryServiceFake.java
> +public class CountryServiceFake implements CountryService  {
the same here

2023-06-14 10:32 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/fake/CityServiceFake.java
> +public class CityServiceFake implements CityService {
the same here

2023-06-14 10:39 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/service/fake/AirportServiceFake.java
> +public class AirportServiceFake implements AirportService {
Renamed

2023-06-14 10:39 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/service/fake/CountryServiceFake.java
> +public class CountryServiceFake implements CountryService  {
Renamed

2023-06-14 10:39 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/service/fake/CityServiceFake.java
> +public class CityServiceFake implements CityService {
Renamed

2023-06-14 10:55 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/persistence/mongo/MongoAirportRepository.java
> +@Profile("!test")
Checked again and removed unnecessary annotations.

2023-06-14 11:34 UTC, h1alexbel approved these changes

2023-06-14 11:35 UTC, merged